Format all documents
NixOS-CN/nixos-cn.github.io pull request #35
Opened 2024-07-01 10:54 UTC by TatooiNoyo

## 目的🎯

- 格式化项目的所有文件，使布局不被破坏。
- 在后续的提交中，因使用自动prettier格式化时，使其提交差异最小化。

## 具体已实现🎐

1. 已将项目所有文件格式化了一遍。
2. 肉眼检查了一遍通过`pnpm run docs:dev`渲染的所有文档。

---

希望其他人可以🔍过一遍。

2024-07-03 10:05 UTC, linyinfeng requested changes

2024-07-03 10:05 UTC, linyinfeng commented on src/tutorials/concept/BinaryAndSourceDistribution.md
> +::: tip
我注意到很多地方用了行末两个空格的方法来产生硬换行，这是必要的么，我尝试删掉一些空格，没有发现布局产生变化？这种用法应当被避免，一个理由是这种用法肉眼不可见，另一个理由是有些人的编辑器配置会 trim 掉行末的空格。

2024-07-03 14:08 UTC, TatooiNoyo commented on src/tutorials/concept/BinaryAndSourceDistribution.md
> +::: tip
在必要的行后增加两空格是为了规避 prettier 格式化时对诸如`:::`（vuepress中格式块标记）的破坏，而采取避免因长句拆分被合并到同一行的手段。
删去行后的两空格而未对布局影响是因为前后行没有需要拆分的长句子（该pr中的长句已被格式化成不同行）。
一个被 prettier 格式化产生布局影响的例子：
```makdwon
::: note
这是一段十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长十分长的句子。它会被 prettier 认定为需要重新分段，在格式化完毕后渲染将影响预期排版。
:::
```
尝试将上诉例子放到项目中，对比格式化前后的区别。

2024-07-05 10:33 UTC, ryan4yin commented on src/tutorials/concept/BinaryAndSourceDistribution.md
> +::: tip
我发现加这个 [\<!-- prettier-ignore -->](https://prettier.io/blog/2017/11/07/1.8.0.html) 也能实现同样的效果，感觉是更好的解法?

```
<!-- prettier-ignore -->
::: tip 立即求值
在文件求值的情景下可以通过在命令行添加 `--strict` 参数来启用立即求值。

```bash
$ echo "{ a.b.c = 1; }" > file.nix
$ nix-instantiate --eval --strict file.nix
{ a = { b = { c = 1; }; }; }
```

如上所示，我测试了在 `:::` 格式块的上一行添加 `<!-- prettier-ignore -->` 也能规避 prettier 的格式化行为。
```

2024-07-05 10:38 UTC, ryan4yin commented
渲染效果与 prettier 格式化我验证了都没问题，等「行末空格」问题解决后可以合并。

2024-07-05 13:11 UTC, TatooiNoyo commented on src/tutorials/concept/BinaryAndSourceDistribution.md
> +::: tip
我尝试重头开始使用`<!-- prettier-ignore -->`仅忽略vue的格式块来测试，如果没问题我会将清除所有行尾软换行标识并为所有vue格式块上一行加上`<!-- prettier-ignore -->`。

2024-07-08 01:39 UTC, merged

2024-07-08 01:40 UTC, ryan4yin commented
没毛病，感谢 @TatooiNoyo 的贡献 ❤️